language: go

services:
  - mysql

go:
  - tip

sudo: false

env:
  - GIN_MODE=release

env:
  - FRACK_TEST_DB=travis@/fracktest

before_install:
  - cd server
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - go get github.com/Masterminds/glide
  - mysql -utravis -h127.0.0.1 -e "CREATE DATABASE fracktest"

script:
  - glide up
  - go build
  - go test
  - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then  bash $TRAVIS_BUILD_DIR/.travis/test-coverage.sh; fi
