language: go

services:
  - mysql

go:
  - tip

sudo: false

before_install: cd server
install:
  - go get github.com/Masterminds/glide
  - glide up
  - go build
  - mysql -utravis -h127.0.0.1 -e "CREATE DATABASE fracktest"

script:
  - GIN_MODE="release" FRACK_TEST_DB="travis@/fracktest" go test
