program:
  - name: Pyramid
    comment: |
      The best pyramid workout
    workouts:
      - laps: 6
        length: 400
        percentage: 100
        rest: 1mn active
      - laps: 4
        length: 800
        percentage: 95
        rest: 1mn30 active
      - laps: 2
        length: 1000
        percentage: 90
        rest: 1mn30 active
  - name: 3x800/2x1000/1x2000
    comment: |
      The best underrated workout
    workouts:
      - laps: 3
        length: 800
        percentage: 80
        rest: 1mn30 active
      - laps: 2
        length: 1000
        percentage: 85
        rest: 3mn
      - laps: 1
        length: 2000
        percentage: 90
        rest: 5mn
